// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenu = "menu"

// Menu 后台菜单表
type Menu struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID   int64      `gorm:"column:parent_id;not null;comment:父级ID" json:"parentId"` // 父级ID
	Title      *string    `gorm:"column:title;comment:菜单名称" json:"title"`                 // 菜单名称
	Level      *int32     `gorm:"column:level;comment:菜单级数" json:"level"`                 // 菜单级数
	Sort       *int32     `gorm:"column:sort;comment:菜单排序" json:"sort"`                   // 菜单排序
	Name       string     `gorm:"column:name;not null;comment:前端名称" json:"name"`          // 前端名称
	Icon       *string    `gorm:"column:icon;comment:前端图标" json:"icon"`                   // 前端图标
	Hidden     bool       `gorm:"column:hidden;not null;comment:前端隐藏" json:"hidden"`      // 前端隐藏
	CreateTime *time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"createTime"`
	UpdateTime *time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"updateTime"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
